engines:
  eslint:
    enabled: true
    config:
      config: .eslintrc
    checks:
      indent:
        enabled: false
      import/no-unresolved:
        enabled: false
  duplication:
    enabled: true
    config:
      languages:
      - javascript
        mass_threshold: 40
ratings:
  paths:
  - "server/**/*.js"
exclude_paths:
  - node_modules/**/*
