sudo: required
dist: trusty
language: node_js
services:
  - postgres
before_script:
  - psql -c 'create database dms_test;' -U postgres

node_js:
  - '6'
after_success: ./node_modules/.bin/coveralls --verbose < coverage/lcov.info
